; FreeDmg - PHP Configuration for Large DMG / PKG / ZIP files
upload_max_filesize = 10240M
post_max_size = 10240M
memory_limit = 2048M
max_execution_time = 7200
max_input_time = 7200
file_uploads = On
